### ISSUE TITLE
Doesn't compile with branch-heads/63 or master branch

### ISSUE THREAD

**Issue by traw** [nicotyze/Webrtc-H264Capturer#10]
Tried to build latest (branch-heads/63 or master) branchs from instruction given in `README.md`. But, seems like there are quite few changes need to be done for it to compile successfully, I'm in half way through it, and manged to compile it, but so far couldn't link with `libavformat, libavcodec and libavutil`.  I get following error 
```
> ldd ./out/Default/peerconnection_client
linux-vdso.so.1 =>  (0x00007ffcaa0d5000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f282f61a000)
libavformat.so.58 => not found
libavcodec.so.58 => not found
libavutil.so.56 => not found

```

**Comment by nicotyze** [comment]
The simpe solution is to do something like:
>export  LD_LIBRARY_PATH=$WEBRTC_DIR/src/out/Default

You can also adapt the rpath in peerconnection_client.ninja, for instance:
> find out/ -name "peerconnection_client.ninja" | xargs sed -i "s|ldflags =|ldflags = -Wl,-rpath,$WEBRTC_DIR/src/out/Default|g"
and then recompile:
> ninja -C out/Default peerconnection_client


2017-11-28 5:14 GMT+01:00 traw <notifications@github.com>:
