### ISSUE TITLE
I'm trying to port this to newer versions of webrtc. Any tips?

### ISSUE THREAD

**Issue by mortie** [nicotyze/Webrtc-H264Capturer#3]
I'm currently trying to port this to newer versions of the library. The biggest obstacle seems to be that cricket::CapturedFrame was removed in commit f5297a019ea6de709a2bb94793d637bb44538931 (https://codereview.webrtc.org/2262443003/). I can't really find any talk about what replaces it. Do you happen to have anything to point me in the right direction?

**Comment by nicotyze** [comment]
This is attached an archive with quickly updated H.264 capturer files that should work with the M58 release. Please, be aware that this has not be completely integrated and tested... 
[H264_capturer_M58.zip](https://github.com/nicotyze/Webrtc-H264Capturer/files/976490/H264_capturer_M58.zip)

The point is to replace cricket::CapturedFrame  by webrtc::VideoFrame and then to access the pixels thanks to the underlying webrtc::I420Buffer 

hope this helps...
