### ISSUE TITLE
ubuntu 16.04 64 bit ffmpeg build error

### ISSUE THREAD

**Issue by zackxue** [nicotyze/Webrtc-H264Capturer#6]
we use ubuntu 16.04 64bit to build ffmpeg, and has below error, which OS you use to build the application?
out/src/third_party/llvm-build/Release+Asserts/bin/clang is a cross-compiler, use the --enable-cross-compile option.
Only do this if you know what cross compiling means.
C compiler test failed.

**Comment by zackxue** [comment]
and when use this command  gn gen out/Default --args='is_component_ffmpeg=true'
ERROR at //build/config/compiler/compiler.gni:203:8: Undefined identifier
assert(ignore_elf32_limitations || !is_android ||
       ^-----------------------
See //build/config/compiler/BUILD.gn:8:1: whence it was imported.
import("//build/config/compiler/compiler.gni")
^--------------------------------------------
See //build/config/BUILDCONFIG.gn:525:3: which caused the file to be included.
  "//build/config/compiler:default_optimization",

**Comment by zackxue** [comment]
Ubuntu 14.04.3 
Kernel: 3.16.0-59-generic

**Comment by nicotyze** [comment]
Hi,
I've just pushed a new commit which is an update to M55 release. For
unknown reasons, the git checkout to the previous flag does not work
anymore (and produces many errors)...

2017-09-26 2:50 GMT+02:00 zackxue <notifications@github.com>:
