### ISSUE TITLE
Conductor.cc patch contains wrong include file name

### ISSUE THREAD

**Issue by sasmaster** [nicotyze/Webrtc-H264Capturer#9]
In the patch there is an include 
#include "webrtc/examples/peerconnection/client/h264videocapturer_dual.h"

I don't see such a file name in the latest update. Is it a typo,or you forgot to rename?

**Comment by sasmaster** [comment]
Well,this time nothing is showing up at all. And there is "vector out of range" error after several seconds inside h264_encoder_impl.cc

**Comment by nicotyze** [comment]
Thanks for catching that. I've just committed the change, this was a
residue of experiments with a dual (SD/HD) capturer...

2017-11-11 13:00 GMT+01:00 Michael Ivanov <notifications@github.com>:

**Comment by sasmaster** [comment]
uint8_t nal = p_nal[NALUidx[nal_index].payload_start_offset];
the nal_index equals 4 while NALUidx size is 4 as well.

**Comment by sasmaster** [comment]
Here is the video I use for tests (it is free to use) 
https://www.dropbox.com/s/o4bvc4h6ewvc0xm/big_buck_bunny.mp4?dl=0

**Comment by sasmaster** [comment]
And if I remove this line from webrtcvideoengine.cc

	if (codec.name == kH264CodecName) {

Then the video shows up.But still only the green noise.

**Comment by nicotyze** [comment]
Thanks for the bug report. I can't get it either with this video (no crash
but no image...). I don't have time to investigate right now but from my
side I mostly tested it with live streams, e.g.:
> gst-launch-1.0 videotestsrc  !
video/x-raw,framerate=30/1,width=640,height=480 ! x264enc tune=zerolatency
bframes=0 key-int-max=30 bitrate=500 !  'video/x-h264,profile=baseline' !
h264parse !  rtph264pay config-interval=1  mtu=1400 ! udpsink
host=127.0.0.1 port=1234
and launched the client as follows:
> ./out/Default/peerconnection_client  --video_url pi.sdp
I attach the sdp file to this message.

2017-11-11 15:25 GMT+01:00 Michael Ivanov <notifications@github.com>:

**Comment by nicotyze** [comment]
I think that the mp4 muxing in this is file  is not well supported by the
ffmpeg frame parsing in h264framegenerator.cc
<https://github.com/nicotyze/Webrtc-H264Capturer/blob/master/H264_capturer/h264framegenerator.cc>
I cannot upgrade the parser quickly but I've extracted the h.264 elementary
stream as follows:
> ffmpeg -i big_buck_bunny.mp4 -vcodec copy -an -f h264 big_buck_bunny.264
and then using the .264 file as input, it seems to work

2017-11-11 21:31 GMT+01:00 nicolas tizon <nicolas.tizon@gmail.com>:
